export const EMPLOYEES_ROUTE = '/employees'
export const ACCOUNTING_ROUTE = '/accounting'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SERVICES_ROUTE = '/services'
export const SERVICE_ROUTE = '/services'
export const FAQ_ROUTE = '/faq'
export const MAIN_ROUTE = '/'
