export const COMPANY_ROUTE = '/company'
export const CLIENT_ROUTE = '/client'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SERVICES_ROUTE = '/services'
export const SERVICE_ROUTE = '/services'
export const FAQ_ROUTE = '/faq'
export const MAIN_ROUTE = '/'
